# Azure Pipelines to build & publish a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - 'master'
  paths:
    include:
    - '.azure/azp-base.xml'
  tags:
    include:
    - 'temp-*'
    - 'test-*'

resources:
- repo: self

variables:
  baseDockerfileDir: './dockeragent/ubuntu/18.04'
  dockerFile: 'Dockerfile'
  imageName: 'azpagent-base'
  imageVersion: '1.0'
  publishDockerHub: ${{ eq(Build.SourceBranch, "refs/heads/build-image-base") }}

stages:
# - stage: Test
#   displayName: Test login docker registry
#   jobs:
#   - job: Test
#     displayName: Test
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#       - script: |
#           echo BuildId '$(Build.BuildId)'
#           echo Build.SourceBranch '$(Build.SourceBranch)'
#           echo Build.SourceVersion '$(Build.SourceVersion)'
#           echo 'refs/heads/build-image-base'
#       - template: 'azp-templates/_step_install_docker_cli.yaml'
#       - task: Docker@2
#         displayName: Login to Docker Hub
#         inputs:
#           command: login
#           containerRegistry: dockerRegistryServiceConnectionDockerHub
- template: 'azp-templates/build-and-publish-image.yaml'
  parameters:
    contextDir: '$(Build.SourcesDirectory)/$(baseDockerfileDir)'
    dockerFile: '$(dockerFile)'
    imageName: '$(imageName)'
    imageVersion: '$(imageVersion)'
    publishDockerHub: $(publishDockerHub)
