# Azure Pipelines to build & publish a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# Image: azpagent-base

# Monitor changes to file '.azure/azp-base.yml' on all branches.
# If change is made to branch 'master' (PR or direct push): push image to DockerHub.
# No need to monitor PRs or tags as we monitor all branches.
# Need 2 env variables from external:
# - DOCKERHUB_REPO: DockerHub username followed by slash (e.g. btnguyen2k/)
# - DOCKERHUB_CONN_NAME: name of Azure DevOps service connection to DocherHub (e.g. myDockerHubConnection)

# pr:
#   branches:
#     include:
#     - 'master'
#   paths:
#     include:
#     - '.azure/azp-base.yml'

trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - '.azure/azp-base.yml'
  # tags:
  #   include:
  #   - 'temp-*'
  #   - 'test-*'

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

variables:
  baseDockerfileDir: './dockeragent/ubuntu/18.04'
  dockerFile: 'Dockerfile'
  imageRepo: $(DOCKERHUB_REPO)
  imageName: 'azpagent-base'
  imageVersion: '1.0'
  pushDockerHub: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/master') }}
  dockerHubConnection: $(DOCKERHUB_CONN_NAME)

stages:
- template: 'azp-templates/build-and-push-image.yml'
  parameters:
    contextDir: '$(Build.SourcesDirectory)/$(baseDockerfileDir)'
    dockerFile: '$(dockerFile)'
    repository: '$(imageRepo)$(imageName)'
    imageVersion: '$(imageVersion)'
    pushDockerHub: ${{ eq(variables['pushDockerHub'], True) }}
    dockerHubConnection: '$(dockerHubConnection)'
