# Azure Pipelines to build & publish a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - 'master'
  paths:
    include:
    - '.azure/azp-base.xml'
  tags:
    include:
    - 'temp-*'
    - 'test-*'

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

variables:
  baseDockerfileDir: './dockeragent/ubuntu/18.04'
  dockerFile: 'Dockerfile'
  imageName: 'azpagent-base'
  imageVersion: '1.0'
  pushDockerHub: ${{ eq(variables['Build.SourceBranch'], 'refs/tags/temp-1.3') }}
  dockerHubConnection: 'dockerRegistryServiceConnectionDockerHub'
  dockerHubUsername: 'btnguyen2k'

stages:
- template: 'azp-templates/build-and-push-image.yaml'
  parameters:
    contextDir: '$(Build.SourcesDirectory)/$(baseDockerfileDir)'
    dockerFile: '$(dockerFile)'
    imageName: '$(imageName)'
    imageVersion: '$(imageVersion)'
    pushDockerHub: ${{ eq(variables['pushDockerHub'], True) }}
    dockerHubConnection: '$(dockerHubConnection)'
    dockerHubUsername: '$(dockerHubUsername)'

