# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - 'master'
  paths:
    include:
    - '.azure/azp-base.xml'
  tags:
    include:
    - 'temp-*'
    - 'test-*'

resources:
- repo: self

variables:
  baseDockerfileDir: './dockeragent/ubuntu/18.04'
  dockerFile: 'Dockerfile'
  imageName: 'azpagent-base'
  imageVersion: '1.0'
  tag: '$(Build.BuildId)'

stages:
- template: 'azp-templates/build-image.yaml'
  parameters:
    contextDir: '$(Build.SourcesDirectory)/$(baseDockerfileDir)'
    dockerFile: '$(dockerFile)'
    imageName: '$(imageName)'
