# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    includes:
    - '*'
  tags:
    includes:
    - 'release-*'
    - 'temp-*'

resources:
- repo: self

variables:
  imageName: azpagent-base
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/dockeragent/ubuntu/18.04/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: List images
      inputs:
        command: images
