parameters:
  contextDir: '<required>'
  dockerFile: '<required>'
  imageName: '<required>'
  imageVersion: '<required>'

jobs:
- job: Build_Docker_image
  displayName: Build and Docker image
  steps:
  - task: Docker@2
    displayName: Build image
    inputs:
      command: build
      arguments: '--rm'
      buildContext: '${{ parameters.contextDir }}'
      Dockerfile: '${{ parameters.contextDir }}/${{ parameters.dockerFile }}'
      repository: '${{ parameters.imageName }}'
      tags: |
        ${{ parameters.imageVersion }}
        latest
  - task: Docker@2
    displayName: List images
    inputs:
      command: images
