parameters:
  dockerFile: '<required>'
  imageName: '<required>'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        dockerfile: '${{ parameters.dockerFile }}'
        tags: |
          ${{ parameters.imageName }}:latest
    - task: Docker@2
      displayName: List images
      inputs:
        command: images
