parameters:
  contextDir: '<required>'
  dockerFile: '<required>'
  imageName: '<required>'
  imageVersion: '<required>'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: '_step_install_docker_cli.yaml'
    - template: '_step_build_docker_image.yaml'
      parameters:
        contextDir: '${{ parameters.contextDir }}'
        dockerFile: '${{ parameters.dockerFile }}'
        imageName: '${{ parameters.imageName }}'
        imageVersion: '${{ parameters.imageVersion }}'
    - task: Docker@2
      displayName: List images
      inputs:
        command: images
