parameters:
  dockerFile: '<required>'
  imageName: '<required>'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: GoTool@0
      displayName: Install Golang
      inputs:
        version: '1.13'
    - task: DockerInstaller@0
      displayName: Install Docker CLI
      inputs:
        dockerVersion: 19.03.9-ce
        releaseType: stable
    - script: |
        go version
        docker version
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        dockerfile: '${{ parameters.dockerFile }}'
        tags: '${{ parameters.imageName }}:latest'
    - task: Docker@2
      displayName: List images
      inputs:
        command: images
