parameters:
  dockerFile: '<required>'
  imageName: '<required>'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        git tag --sort=-creatordate
        echo Build.SourceVersion: $(Build.SourceVersion)
        git describe --exact-match $(Build.SourceVersion)
        echo Build.SourceBranch: $(Build.SourceBranch)
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/dockeragent/ubuntu/18.04/Dockerfile'
    #     tags: |
    #       $(tag)
    # - task: Docker@2
    #   displayName: List images
    #   inputs:
    #     command: images
