parameters:
  contextDir: '<required>'
  dockerFile: '<required>'
  imageName: '<required>'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: GoTool@0
      displayName: Install Golang
      inputs:
        version: '1.13'
    - task: DockerInstaller@0
      displayName: Install Docker CLI
      inputs:
        dockerVersion: '19.03.9'
        releaseType: 'stable'
    - script: |
        go version
        docker version
    - script: docker build --rm -t '${{ parameters.imageName }}:latest' -f '${{ parameters.contextDir }}/${{ parameters.dockerFile }}' '${{ parameters.contextDir }}'
      displayName: Build image
    # - task: Docker@2
    #   displayName: Build image
    #   inputs:
    #     command: build
    #     dockerfile: '${{ parameters.dockerFile }}'
    #     tags: '${{ parameters.imageName }}:latest'
    - task: Docker@2
      displayName: List images
      inputs:
        command: images
