parameters:
  contextDir: '<required>'
  dockerFile: '<required>'
  repository: '<required>'
  imageVersion: '<required>'
  pushDockerHub: false
  dockerHubConnection: '<required if pushDockerHub>'
  pushACR: false

stages:
- stage: Build_and_Push
  displayName: Build and Push Docker image
  jobs:
  - job: Build_and_Push
    displayName: Build and Push Docker image
    steps:
    - template: '_task_install_docker_cli.yml'
    - template: '_task_build_docker_image.yml'
      parameters:
        contextDir: '${{ parameters.contextDir }}'
        dockerFile: '${{ parameters.dockerFile }}'
        repository: '${{ parameters.repository }}'
        imageVersion: '${{ parameters.imageVersion }}'
    - task: Docker@2
      displayName: List images
      inputs:
        command: images
    - ${{ if eq(parameters.pushDockerHub, true) }}:
      - template: '_task_push_to_dockerhub.yml'
        parameters:
          dockerHubConnection: '${{ parameters.dockerHubConnection }}'
          repository: '${{ parameters.repository }}'
          imageVersion: '${{ parameters.imageVersion }}'
