parameters:
  contextDir: '<required>'
  dockerFile: '<required>'
  imageName: '<required>'
  imageVersion: '<required>'
  publishDockerHub: false
  dockerHubConnection: '<required if publishDockerHub>'
  publishACR: false

stages:
- stage: Build_and_Publish
  displayName: Build and Publish Docker image
  jobs:
  - job: Build_and_Publish
    displayName: Build and Publish Docker image
    steps:
    - template: '_task_install_docker_cli.yaml'
    # - template: '_task_build_docker_image.yaml'
    #   parameters:
    #     contextDir: '${{ parameters.contextDir }}'
    #     dockerFile: '${{ parameters.dockerFile }}'
    #     imageName: '${{ parameters.imageName }}'
    #     imageVersion: '${{ parameters.imageVersion }}'
    - task: Docker@2
      displayName: List images
      inputs:
        command: images
    - ${{ if eq(parameters.publishDockerHub, true) }}:
      - template: '_task_push_to_dockerhub.yaml'
        parameters:
          dockerHubConnection: '${{ parameters.dockerHubConnection }}'
