parameters:
  contextDir: '<required>'
  dockerFile: '<required>'
  imageName: '<required>'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerInstaller@0
      displayName: Install Docker CLI
      inputs:
        dockerVersion: '19.03.9'
        releaseType: 'stable'
    - script: docker build --rm -t '${{ parameters.imageName }}:latest' -f '${{ parameters.contextDir }}/${{ parameters.dockerFile }}' '${{ parameters.contextDir }}'
      displayName: Build image
    - task: Docker@2
      displayName: List images
      inputs:
        command: images
