parameters:
  contextDir: '<required>'
  dockerFile: '<required>'
  imageName: '<required>'
  imageVersion: '<required>'
  publishDockerHub: False
  publishACR: False

stages:
- stage: Build_and_Publish
  displayName: Build and Publish Docker image
  jobs:
  - job: Build_and_Publish
    displayName: Build and Publish Docker image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: '_step_install_docker_cli.yaml'
    - ${{ if eq(parameters.publishDockerHub, True) }}:
      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: login
          containerRegistry: dockerRegistryServiceConnectionDockerHub
    # - template: '_step_build_docker_image.yaml'
    #   parameters:
    #     contextDir: '${{ parameters.contextDir }}'
    #     dockerFile: '${{ parameters.dockerFile }}'
    #     imageName: '${{ parameters.imageName }}'
    #     imageVersion: '${{ parameters.imageVersion }}'
    - task: Docker@2
      displayName: List images
      inputs:
        command: images
